name: Gh-Pages

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 # Only works with v2
      - uses: subosito/flutter-action@v1
      - uses: viviethoang99/flutter-gh-pages@v3
        with:
          baseHref: /web_optimize/
          assetBase: web_optimize/